[package]
name = "dev-sandbox"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
tokio-util = { version = "0.7.17", features = ["full"] }
