[package]
name = "dev-sandbox"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/kv", "crates/log", "crates/tests"]

[workspace.dependencies]
log = { path = "./crates/log" }
kv = { path = "./crates/kv" }
chrono = "0.4.42"

[dependencies]
kv.workspace = true
log.workspace = true
